version: 0.2
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install
      - npm run build
